-- Create departments table if it doesn't exist
create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert existing departments (safe to run multiple times due to ON CONFLICT)
insert into departments (name) values
('KSB'),
('BIDANG PA'),
('BIDANG PAO'),
('BIDANG KOMDIG'),
('BIDANG KPP'), 
('BIDANG PTKP'),
('BIDANG PPD'),
('BIDANG PU'),
('BIDANG HUMHAM')
on conflict (name) do nothing;

-- Add linkedin column to members table if it doesn't exist
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'members' and column_name = 'linkedin') then
    alter table members add column linkedin text;
  end if;
end $$;
